### ISSUE TITLE
pysteps error when installed cartopy 

### ISSUE THREAD

**Issue by diversoft** [pySTEPS/pysteps#201]
1、warning message when execute “python .\plot_extrapolation_nowcast.py” without cartopy 
<class 'pysteps.exceptions.MissingOptionalDependency'>: the cartopy package is required to plot the geographical map  but it is not installed
2、installed cartopy
![image](https://user-images.githubusercontent.com/2303685/103848425-4cb72e80-50dd-11eb-8533-5e05f18b45ce.png)

3、pysteps errors：
`(floods) PS E:\pysteps_data\pysteps_data> python .\plot_extrapolation_nowcast.py
Traceback (most recent call last):
  File ".\plot_extrapolation_nowcast.py", line 15, in <module>
    from pysteps import io, motion, nowcasts, rcparams, verification
  File "d:\ProgramData\Anaconda3\envs\floods\lib\site-packages\pysteps\__init__.py", line 25, in <module>
    from . import visualization as plt
  File "d:\ProgramData\Anaconda3\envs\floods\lib\site-packages\pysteps\visualization\__init__.py", line 4, in <module>
    from .motionfields import *
  File "d:\ProgramData\Anaconda3\envs\floods\lib\site-packages\pysteps\visualization\motionfields.py", line 19, in <module>
    from . import basemaps
  File "d:\ProgramData\Anaconda3\envs\floods\lib\site-packages\pysteps\visualization\basemaps.py", line 22, in <module>
    import cartopy.crs as ccrs
  File "d:\ProgramData\Anaconda3\envs\floods\lib\site-packages\cartopy\__init__.py", line 96, in <module>
    import cartopy.crs
  File "d:\ProgramData\Anaconda3\envs\floods\lib\site-packages\cartopy\crs.py", line 2418, in <module>
    Sinusoidal.MODIS = Sinusoidal(globe=Globe(ellipse=None,
  File "d:\ProgramData\Anaconda3\envs\floods\lib\site-packages\cartopy\crs.py", line 2392, in __init__
    self._boundary = sgeom.LinearRing(points)
  File "d:\ProgramData\Anaconda3\envs\floods\lib\site-packages\shapely\geometry\polygon.py", line 55, in __init__
    self._set_coords(coordinates)
  File "d:\ProgramData\Anaconda3\envs\floods\lib\site-packages\shapely\geometry\polygon.py", line 70, in _set_coords
    ret = geos_linearring_from_py(coordinates)
  File "shapely\speedups\_speedups.pyx", line 408, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: GEOSGeom_createLinearRing_r returned a NULL pointer`

**Comment by diversoft** [comment]
1、I download .whl file from [Python Extension Packages for Windows - Christoph Gohlke](https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely)
Shapely-1.7.1-cp38-cp38-win_amd64.whl
2、I uninstall shapely
pip uninstall C:\Users\xyzbo\Downloads\Shapely-1.7.1-cp38-cp38-win_amd64.whl
3、install shapely
pip install C:\Users\xyzbo\Downloads\Shapely-1.7.1-cp38-cp38-win_amd64.whl

ok
