### ISSUE TITLE
utils/interface.py fails with default dependencies 

### ISSUE THREAD

**Issue by dnerini** [pySTEPS/pysteps#29]
https://github.com/pySTEPS/pysteps/blob/58ef4a7fc6bda8df1931e5efe800f0425799b565/pysteps/utils/interface.py#L102

The utils/interface.py causes the program to fail when only the default dependencies are installed:

> Traceback (most recent call last):
  File "run_ensemble_nowcast.py", line 85, in <module>
    reshaper = stp.utils.get_method(adjust_domain)
  File "/home/ned/anaconda3/envs/pysteps/lib/python3.6/site-packages/pysteps/utils/interface.py", line 102, in get_method
    methods_objects["pyfftw_fft"]   = fft.get_method("pyfftw")
  File "/home/ned/anaconda3/envs/pysteps/lib/python3.6/site-packages/pysteps/utils/fft.py", line 45, in get_method
    raise MissingOptionalDependency("pyfftw is required but it is not installed")
pysteps.exceptions.MissingOptionalDependency: pyfftw is required but it is not installed

 This is a bug, as pyfftw is in fact an optional package. We'll need to fix this before the next release. Not sure what would be the best way to address this issue, any thoughts @pulkkins? 

Part of the problem might be that we currently have two get_method() in utils: one in utils/interface.py and one in the utils/fft.py module. For consistency with the other modules, only the get_method() in utils/interface.py should be kept.

**Comment by dnerini** [comment]
Solved by commit 6a468e8f117df4b781c36e174e7adf7eb775c9ce, thanks @pulkkins.
