### ISSUE TITLE
Problem with PAAH22_C_EUOC new OPERA file

### ISSUE THREAD

**Issue by olgalaki** [pySTEPS/pysteps#439]
When I tried to import OPERA PAAH22_C_EUOC hdf file in proba_rain.py error appear:

Traceback (most recent call last):
  File "/home/radar/pysteps/proba_rain.py", line 125, in <module>
    main()
  File "/home/radar/pysteps/proba_rain.py", line 78, in main
    R, quality, metadata = io.read_timeseries(fns, importer, **importer_kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/radar/.conda/envs/pysteps/lib/python3.11/site-packages/pysteps/io/readers.py", line 53, in read_timeseries
    precip_ref, quality_ref, metadata = importer(ifn, **kwargs)
                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/radar/.conda/envs/pysteps/lib/python3.11/site-packages/pysteps/decorators.py", line 70, in _import_with_postprocessing
    precip, *other_args = importer(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/radar/.conda/envs/pysteps/lib/python3.11/site-packages/pysteps/io/importers.py", line 1364, in import_odim_hdf5
    ) = _read_opera_hdf5_what_group(dgg[1]["what"])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/radar/.conda/envs/pysteps/lib/python3.11/site-packages/pysteps/io/importers.py", line 1483, in _read_opera_hdf5_what_group
    qty = whatgrp.attrs["quantity"]
          ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/radar/.conda/envs/pysteps/lib/python3.11/site-packages/h5py/_hl/attrs.py", line 56, in __getitem__
    attr = h5a.open(self._id, self._e(name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 80, in h5py.h5a.open
KeyError: "Can't open attribute (can't locate attribute: 'quantity')"

Could you help me with this problem?

**Comment by dnerini** [comment]
hi @olgalaki, it's very plausible that a new OPERA version broke our importer. Do you know where this new version is documented? Can you share an example file?

**Comment by olgalaki** [comment]
I found documentation on Opera's web page:
 https://www.eumetnet.eu/wp-content/uploads/2024/06/NIMBUS_composite_vs_ODYSSEY_1.0_19062024.pdf
The difference between old and new file is described here.

I attached one example file:
[T_PAAH22_C_EUOC_20241112060000.zip](https://github.com/user-attachments/files/17712924/T_PAAH22_C_EUOC_20241112060000.zip)

**Comment by dnerini** [comment]
Hi @olgalaki very good thanks, let me ask, would you be willing to contribute on this issue?

**Comment by olgalaki** [comment]
Hi @dnerini, 
I would like to contribute on this issue but I'm beginner in programing. Despite I will be available for further cooperation.

**Comment by dnerini** [comment]
Hi @olgalaki thanks for being open about contributing. I unfortunately have little time to dedicate to this currently, so this might need to wait, unless we find somebody else willing to have a look...

**Comment by pulkkins** [comment]
Hi, @olgalaki I'll take a look at this during the coming week.

**Comment by olgalaki** [comment]
@pulkkins  Great, thanks.

**Comment by pulkkins** [comment]
I created a branch for the new version of OPERA importer: https://github.com/pySTEPS/pysteps/tree/opera_fixes. It should now work for the new CIRRUS and NIMBUS products. I'll make a pull request.

**Comment by olgalaki** [comment]
@pulkkins It's working, thanks a lot!
